apiVersion: v1
kind: Service
metadata: 
  name: nginx-cluster-ip

spec: 
  type: ClusterIp
  selector: 
    app: db
  ports: 
    - port: 8080  # service port
      targetPort: 80  #pod/container port