apiVersion: v1
kind: Service
metadata: 
  name: node-port-service
spec:
  type: NodePort
  selector: 
    app: my-web-app

  ports: 
    - port: 8080      #cluster ip service port
      targetPort: 80 #pod/container port
      nodePort: 30005  #any port between 30000 and 32767


    

























